### ISSUE TITLE
haskell-ghc-mod not working after installing and configured

### ISSUE THREAD

**Issue by betlgtu** [lierdakil/haskell-ghc-mod#2]
**Atom Version**: 0.179.0
**System**: Windows 7
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.4.1

1. After installing haskell-ghc-mod I see following error:

### Stack Trace

Uncaught Error: Error: Command failed: C:\Users\Bet\AppData\Roaming\cabal\bin\ghc-mod.exe browse -d Import
retrieval of the cabal configuration flags failed: extractField: failed extracting configFlags from input, input contained `configFlags'? False

```
At /C:/Users/Bet/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:124

Error: Error: Command failed: C:\Users\Bet\AppData\Roaming\cabal\bin\ghc-mod.exe browse -d Import
retrieval of the cabal configuration flags failed: extractField: failed extracting configFlags from input, input contained `configFlags'? False

  at C:\Users\Bet\.atom\packages\haskell-ghc-mod\lib\ghc-modi-process.coffee:69:17
  at ChildProcess.exithandler (child_process.js:756:5)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -9:55.1 ide-haskell:check-file (atom-text-editor.editor)
 14x -7:47.5 core:backspace (atom-text-editor#ide-haskell.ghcModPath.editor.mini)
  2x -7:41.4 core:save (atom-text-editor#ide-haskell.stylishHaskellPath.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai-dark"
    ]
  },
  "haskell-ghc-mod": {
    "ghcModPath": "C:\\Users\\Bet\\AppData\\Roaming\\cabal\\bin\\ghc-mod.exe",
    "ghcModiPath": "C:\\Users\\Bet\\AppData\\Roaming\\cabal\\bin\\ghc-modi.exe"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.2.0
autocomplete-plus, v2.1.6
git-projects, v1.7.1
git-tab-status, v1.5.3
haskell-ghc-mod, v0.4.1
ide-haskell, v0.3.2
language-haskell, v1.0.0
language-powershell, v1.0.0
linter-hlint, v0.3.1
monokai-dark, v1.0.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
This looks to be a problem with ghc-mod. Try removing dist folder and reconfiguring your project. (see e.g. Atsky/haskell-idea-plugin#77)

**Comment by betlgtu** [comment]
I create test haskell project, plugin works OK.
I create scaffolded yesod web-application, and see error.
When I delete dist folder and reconfiguring my yesod project, the error not showing, but I can't see type information about any of variable.

**Comment by betlgtu** [comment]
I change Expression Type Interval to 1000 and all OK.

**Comment by lierdakil** [comment]
So, can I close this then?

**Comment by betlgtu** [comment]
Yes, Plugin work correctly. Good Plugin
