### ISSUE TITLE
Uncaught Error: Error: spawn ghc-mod ENOENT

### ISSUE THREAD

**Issue by rhvall** [lierdakil/haskell-ghc-mod#5]
1. I just opened a bash script with atom and it gave me this error, I hope it helps 

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.4.3

### Stack Trace

Uncaught Error: Error: spawn ghc-mod ENOENT

```
At /Users/RValencia/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:70

Error: Error: spawn ghc-mod ENOENT
  at /Users/RValencia/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:70:17
  at exithandler (child_process.js:756:5)
  at ChildProcess.errorhandler (child_process.js:763:5)
  at ChildProcess.emit (events.js:116:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1070:12)
  at child_process.js:1142:20
  at process._tickCallback (node.js:366:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.2.1
autocomplete-plus, v2.4.1
haskell-ghc-mod, v0.4.3
haskell-grammar, v0.3.0
haskell-pointfree, v0.1.0
ide-haskell, v0.3.5
language-glsl, v1.0.1
language-haskell, v1.0.0
language-opencl, v0.1.0
language-r, v0.1.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
It basically means that Atom could not find `ghc-mod` executable. Not sure why Atom attempted to spawn it on a bash script though.

**Comment by lierdakil** [comment]
You also should probably use `language-haskell` instead of `haskell-grammar` as well, since `ide-haskell` and `haskell-ghc-mod` both rely on it.

**Comment by rhvall** [comment]
I removed the ```haskell-grammar``` package, configured the path for the ```ghc-mod``` and ```stylish-haskell``` and now it does not crash at the beginning. Although I am still not able to get full functionality (configuration issues), this issue was solved.

Thanks and great job!!
